### ISSUE TITLE
backward digit span task

### ISSUE THREAD

**Issue by Abdolnoor** [mahiluthra/working_memory_tests#1]
Hi, 

I just wanted to change the code to run backward digit span test through changing allow_backward: false into true but I faced the error: jspsych is not defined in visual studio code. First, I am not sure it is enough to change or not?! Second how I can solve the problem?!

**Comment by mahiluthra** [comment]
Hi. The current version of the code does not do backward digit span test. The allow_backward variable that you changed from False to True enables the instructions to move back and forth and does not change the digit span test into a backward digit span test.

If you want to convert the test into a backward digit span test, do the following:
(1) Change line 111 to _return selection.reverse()_ from _return selection_
(2) Change instructions to correctly reflect the task
