### ISSUE TITLE
Running digit_span on cognition.run

### ISSUE THREAD

**Issue by Abdolnoor** [mahiluthra/working_memory_tests#2]
Hi,
I wanted to copy the codes on text editor on the website cognition.run, but it did not worked or said it is not yet ready. Do you know how to run and implement the backward experiment on the the website using your existing code. It seems that it doesnt need html there to run but I do not know about that. Could you please say how your codes for doing a backward task might work there. I have changed the required code online 111.

**Comment by mahiluthra** [comment]
Hi to run this experiment on cognition.run, do the following:

1) Create an account and a new task.
2) Click on Source Code of the task
3) Upload all supporting .js and .css files--these are in the plugins and css folder within the jspsych-6.0.4 folder. From the css folder, **only upload jspsych_digitspan.css** (uploading all the other css files for other tasks will mess up the formatting).
4) Change the jspsych library version to 6.0.5
5) Copy paste all code that is within the <script> tags from digit_span_task.html.
6) If you don not want your participant's data to be downloaded to their local computer, comment out line 226--_timeline.push(dataLog)_

This is the task I created just now following the above steps: https://1plpk9wavy.cognition.run/
You can similarly create your own task!

Let me know if you have more questions.

**Comment by python2020-maker** [comment]
I did what you said in order but it says that the task is not ready yet. Maybe it need to upload the stimuli? if yes, where can I find the stimuli?

**Comment by Abdolnoor** [comment]
I did what you said in order but it says that the task is not ready yet. Maybe it need to upload the stimuli? if yes, where can I find the stimuli?

**Comment by python2020-maker** [comment]
And how should I do if I want to test more numbers with 5 until 11 digits for each trial?

**Comment by Abdolnoor** [comment]
And what should I do if want to add more stumuli with longer digits until 10 digit in each trial for example 123456778     1235589076

**Comment by mahiluthra** [comment]
There is no stimuli for the digit span test. Maybe change the jspysch library version to 6.0.5? I have edited the steps above to include this

**Comment by sepidehnamvarrad** [comment]
Hello!
I tried your code in the cognition run. It gives an uncaught error in line 285. Also, I didn't in general realized what this line is supposed to do. 
partN = partN.replace(/['"]+/g,'')

**Comment by mahiluthra** [comment]
Hi!
Which task are you attempting to run? The digit span test does not have a line 285! Here is a backward digit span test that is working for me on cognition.run: https://1plpk9wavy.cognition.run

The line that you pasted above (_partN = partN.replace(/['"]+/g,''_) simply removes extra quotation marks around the participant name/id. When the task starts, participants are prompted for their id--the previous line (_partN = jsPsych.data.get().last(1).values()[0].partNum_) stores the input as partN and the current line cleans extra quotation marks around that input. Does this make sense? 

If you do not need to store participant id, change line 216 to _timeline = []_ and comment out line 226 (_timeline.push(dataLog)_)

**Comment by Abdolnoor** [comment]
Hi, this is an image of the website with required files and scripts. I am
just wondering why it does not work.

**Comment by mahiluthra** [comment]
Please make sure that you have copy pasted the script from digit_span_task.html properly (step 5 above). You need to copy everything after the <script> tag (from line 16 onward) and before the </script> tag (before and including line 235).

And ensure that you have appropriately added all the supporting files (step 3 above).

Please let me know if it starts working.

**Comment by mahiluthra** [comment]
I cannot see the image that you have posted and I am therefore unsure what error you are running into.
